### ISSUE TITLE
Make the temporary folder where files are saved configurable

### ISSUE THREAD

**Issue by maurelio1234** [andrewallred/allez#6]
This is another thing I needed to fix on my fork.
On AWS I can't write on the filesystem, and the folder `./games` is hard coded.
I changed that to `/tmp` on my fork.

Would `/tmp` work for your use cases?
Or you want to support windows users?
What about a env var for overriding your default value ? Like `TEMP_GAMES_FOLDER`?

Or... do you really need to download the file to re-upload it?

**Comment by andrewallred** [comment]
This should be easy enough @maurelio1234. I'd actually be pretty happy if we could avoid downloading the file but for some reason I couldn't figure out how to serialize the game properly in memory and upload it as form data, so that was the "get it working" solution. For now I'll go ahead and make this configurable though and could look at a better solution later.

**Comment by andrewallred** [comment]
@maurelio1234 went ahead and made this change on main, you can check it out here https://github.com/andrewallred/allez/commit/e0f9602e10a906afe6793b2060104e4033f16aeb
